#!/usr/bin/env python3
"""gen_hoth_rancor.py — Hoth world boss: Infinity's spiked "exotic rancor" (the NGE mutant-rancor-boss mesh re-rigged).
Idempotent.

  client(): stage object/mobile/shared_exotic_rancor.iff and its asset closure from Infinity into build/hoth_loot
            (called by gen_hoth_loot_client.py)
  server(): object templates, the mobile (mobile/hoth/hoth_glacial_rancor.lua; included by gen_hoth_mobiles.py) and
            the world boss screenplay (mirrors AcklayWorldBossLoot: engine respawn, WorldBossLootManager per-player
            rewards, galaxy broadcasts). Every eligible player also gets the Hoth bonus roll (gen_boss_loot.py hook).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import gen_hoth_mobiles as g

CLIENT_OBJ = 'object/mobile/shared_exotic_rancor.iff'
SERVER_OBJ = 'object/mobile/exotic_rancor.iff'
KEY = 'hoth_glacial_rancor'
NAME = 'Rimeclaw, the Glacial Rancor'
SPAWN = dict(x=600.0, y=-4600.0, z=10.0, heading=200)  # southern ice plain: terrain layer flattens r1800 around (0,-4000) to 10 m
POI = ('glacial_rancor_grounds', 'Glacial Rancor Hunting Grounds', 600, -4600, 200)
SCREENPLAY = 'screenplays/bellum/hoth_glacial_rancor_worldboss.lua'


def client():
    import gen_hoth_loot_client as c
    import gen_hoth_vehicles as v
    inf_paths = {l.split('\t')[1].lower() for l in open(os.path.join(HERE, 'infinity_all.txt'), encoding='utf-8', errors='replace') if '\t' in l}
    bg_paths = {l.split('\t')[1].lower() for l in open(os.path.join(HERE, 'bg_all.txt'), encoding='utf-8', errors='replace') if '\t' in l}
    dev_list = os.path.join(HERE, 'devbg_all.txt')
    if os.path.exists(dev_list):
        bg_paths &= {l.split('\t')[1].lower() for l in open(dev_list, encoding='utf-8', errors='replace') if '\t' in l}
    bg_paths.discard(CLIENT_OBJ)
    staged = v.stage_recursive(c, [CLIENT_OBJ], inf_paths, bg_paths)
    c.NEW_OBJECTS.append(CLIENT_OBJ)
    print(f'glacial rancor: staged {len(staged)} files')
    return staged


MOBILE = f'''-- Generated by NewPlanets/gen_hoth_rancor.py. Hoth world boss; loot is per player via WorldBossLootManager
-- ({SCREENPLAY}), so the corpse carries none.
{KEY} = Creature:new {{
	objectName = "",
	customName = "{NAME}",
	socialGroup = "rancor",
	mobType = MOB_CARNIVORE,
	faction = "",
	level = 350,
	chanceHit = 92.5,
	damageMin = 935,
	damageMax = 1580,
	baseXp = 14884,
	baseHAM = 1000000,
	baseHAMmax = 1500000,
	armor = 2,
	resists = {{170,170,150,200,150,200,75,75,20}},
	meatType = "meat_carnivore",
	meatAmount = 2000,
	hideType = "hide_leathery",
	hideAmount = 1800,
	boneType = "bone_mammal",
	boneAmount = 1600,
	milk = 0,
	tamingChance = 0,
	ferocity = 25,
	pvpBitmask = AGGRESSIVE + ATTACKABLE + ENEMY,
	creatureBitmask = PACK + KILLER,
	optionsBitmask = AIENABLED,
	diet = CARNIVORE,
	tauntable = false,
	templates = {{"{SERVER_OBJ}"}},
	scale = 1.3,
	lootGroups = {{}},
	primaryWeapon = "unarmed",
	secondaryWeapon = "none",
	conversationTemplate = "",
	primaryAttacks = {{
		{{"posturedownattack","stateAccuracyBonus=60"}},
		{{"creatureareaknockdown","stateAccuracyBonus=60"}},
		{{"creatureareacombo","stateAccuracyBonus=60"}},
		{{"intimidationattack",""}}
	}},
	secondaryAttacks = {{ }}
}}

CreatureTemplates:addCreatureTemplate({KEY}, "{KEY}")
'''

SCREENPLAY_LUA = f'''-- Generated by NewPlanets/gen_hoth_rancor.py.
-- {NAME}: Hoth world boss (Infinity's spiked exotic rancor). Mirrors AcklayWorldBossLoot: the engine respawns it,
-- WorldBossLootManager gives every eligible player their own rewards (plus the Hoth bonus roll).
local TAG = "[HOTH-RANCOR-WB]"
local function logf(fmt, ...)
	local s = string.format(TAG .. " " .. fmt, ...)
	if printLuaError then printLuaError(s) else print(s) end
end

local WorldBossLootManager = require("screenplays.managers.world_boss_loot_manager")

HothGlacialRancorWorldBoss = ScreenPlay:new {{
	numberOfActs = 1,
	screenplayName = "HothGlacialRancorWorldBoss",

	planet = "hoth",
	x = {SPAWN['x']}, y = {SPAWN['y']}, z = {SPAWN['z']}, heading = {SPAWN['heading']},

	bossTemplate = "{KEY}",
	bossName = "{NAME}",
	leashRadius = 120,
	respawnSeconds = 86400, -- 24 hours, like the other world bosses

	bootGuardKey = "HothGlacialRancorWorldBoss:booted:v1",
	FIRST_BROADCAST_DELAY = 240,
	REPEAT_EVERY_SECONDS = 10800,
	DATA_BOSS_OID = "HothGlacialRancorWorldBoss:bossOID",
	DATA_NEXT_BCAST_AT = "HothGlacialRancorWorldBoss:nextBcastAt",
	DATA_LOOP_STARTED = "HothGlacialRancorWorldBoss:loopStarted",

	-- WorldBossLootManager: 3 items per player, each from a randomly chosen collection (lootChance is ignored)
	lootGroups = {{
		{{
			groups = {{
				{{group = "krayt_tissue_rare", chance = 3000000}},
				{{group = "color_crystals", chance = 2000000}},
				{{group = "power_crystals", chance = 2000000}},
				{{group = "armor_attachments", chance = 1500000}},
				{{group = "clothing_attachments", chance = 1500000}}
			}},
			lootChance = 10000000
		}},
		{{ groups = {{ {{group = "krayt_pearls", chance = 10000000}} }}, lootChance = 5000000 }},
		{{ groups = {{ {{group = "house_deeds", chance = 10000000}} }}, lootChance = 2000000 }},
		{{ groups = {{ {{group = "endgame_weapon_schematics", chance = 10000000}} }}, lootChance = 1500000 }},
		{{ groups = {{ {{group = "bg_token_group", chance = 10000000}} }}, lootChance = 350000 }}
	}},

	bossPtr = nil
}}

registerScreenPlay("HothGlacialRancorWorldBoss", true)

local function getFlag(k) return (readData and (tonumber(readData(k)) or 0) or 0) end
local function setFlag(k, v) if writeData then writeData(k, v) end end

local function galaxyBroadcast(msg, ctx)
	if type(broadcastToGalaxy) ~= "function" then return false end
	if ctx and pcall(broadcastToGalaxy, ctx, msg) then return true end
	if pcall(broadcastToGalaxy, nil, msg) then return true end
	return pcall(broadcastToGalaxy, msg)
end

function HothGlacialRancorWorldBoss:start()
	if not isZoneEnabled(self.planet) then return end
	if getFlag(self.bootGuardKey) == 1 then
		logf("start(): already booted; skipping duplicate")
		return
	end
	setFlag(self.bootGuardKey, 1)
	self:spawnBoss()
	if getFlag(self.DATA_LOOP_STARTED) ~= 1 then
		setFlag(self.DATA_LOOP_STARTED, 1)
		createEvent(5000, "HothGlacialRancorWorldBoss", "broadcastLoop", nil, "")
	end
end

function HothGlacialRancorWorldBoss:spawnBoss()
	local pBoss = spawnMobile(self.planet, self.bossTemplate, self.respawnSeconds, self.x, self.z, self.y, self.heading, 0)
	if pBoss == nil then
		logf("FATAL: spawnMobile failed")
		return
	end
	local boss = LuaCreatureObject(pBoss)
	if boss and boss.setHomeLocation then
		boss:setHomeLocation(self.x, self.z, self.y, self.leashRadius)
	end
	createObserver(DAMAGERECEIVED, "HothGlacialRancorWorldBoss", "onBossDamaged", pBoss)
	createObserver(OBJECTDESTRUCTION, "HothGlacialRancorWorldBoss", "onBossDeath", pBoss)
	self.bossPtr = pBoss
	setFlag(self.DATA_BOSS_OID, SceneObject(pBoss):getObjectID())
	setFlag(self.DATA_NEXT_BCAST_AT, os.time() + self.FIRST_BROADCAST_DELAY)
	logf("SPAWNED at (%.1f, %.1f, %.1f)", self.x, self.z, self.y)
end

function HothGlacialRancorWorldBoss:onBossDamaged(pBoss, pAttacker, _damage)
	if pBoss == nil or pAttacker == nil then return 0 end
	WorldBossLootManager:trackDamage(pBoss, pAttacker)
	return 0
end

function HothGlacialRancorWorldBoss:onBossDeath(pBoss, pKiller)
	if pBoss == nil then return 0 end
	WorldBossLootManager:onBossDeath(pBoss, self.lootGroups, self.bossName)
	setFlag(self.DATA_NEXT_BCAST_AT, os.time() + self.respawnSeconds + self.FIRST_BROADCAST_DELAY)
	if broadcastMessage then
		broadcastMessage("\\\\#00FF00" .. self.bossName .. " has been slain on Hoth!")
	end
	return 0
end

function HothGlacialRancorWorldBoss:broadcastLoop()
	if not self.bossPtr then
		local oid = tonumber(readData(self.DATA_BOSS_OID) or 0) or 0
		if oid > 0 then self.bossPtr = getSceneObject(oid) end
	end
	local nextBcast = tonumber(readData(self.DATA_NEXT_BCAST_AT) or 0) or 0
	if self.bossPtr and nextBcast > 0 and os.time() >= nextBcast then
		local alive = false
		pcall(function() alive = not CreatureObject(self.bossPtr):isDead() end)
		if alive then
			galaxyBroadcast(string.format("[NOTICE] %s stalks the southern ice plains of Hoth (%.0f, %.0f).",
				self.bossName, self.x, self.y), self.bossPtr)
		end
		setFlag(self.DATA_NEXT_BCAST_AT, os.time() + self.REPEAT_EVERY_SECONDS)
	end
	createEvent(5000, "HothGlacialRancorWorldBoss", "broadcastLoop", nil, "")
	return 0
end
'''


def server():
    import gen_hoth_loot as gl
    n = gl.ensure_shared('object/mobile/objects.lua', [CLIENT_OBJ])
    lid = gl.luaid(SERVER_OBJ)
    g.write('object/mobile/exotic_rancor.lua',
            f'-- Generated by NewPlanets/gen_hoth_rancor.py\n{lid} = {gl.luaid(CLIENT_OBJ)}:new {{\n}}\n\n'
            f'ObjectTemplates:addTemplate({lid}, "{SERVER_OBJ}")\n')
    g.register('object/mobile/serverobjects.lua', 'includeFile("mobile/exotic_rancor.lua")', after_prefix='includeFile("mobile/')
    g.write(f'mobile/hoth/{KEY}.lua', MOBILE)
    g.write(SCREENPLAY, SCREENPLAY_LUA)
    g.register('screenplays/screenplays.lua', f'includeFile("{SCREENPLAY[len("screenplays/"):]}")', after_prefix='includeFile("bellum/')
    print(f'glacial rancor: shared template added {n}, mobile {KEY}, screenplay {SCREENPLAY}')


if __name__ == '__main__':
    server()
