#!/usr/bin/env python3
"""gen_hoth_art.py — custom Hoth boss paintings from reference artwork. Idempotent.

For each entry in ART it writes into build/hoth_loot/:
  texture/hoth_art_<key>.dds                 512x512 DXT1 made from art/<file> (crop or pad to square)
  shader/hoth_art_<key>.sht                  clone of the square Hoth painting shader, texture path swapped
  appearance/mesh/hoth_art_<key>.msh         clone of the square frame mesh, shader path swapped
  appearance/hoth_art_<key>.apt              clone, mesh path swapped
  object/tangible/painting/shared_hoth_art_<key>.iff   clone of the square painting template; names in art_n/art_d
Names/descriptions are exported through names()/descs() for gen_hoth_loot_client.py; the server side
(painting templates, loot items, the hoth_art_rare group) is generated by gen_hoth_loot.py.
Source images live in C:\\SWG-Dev\\NewPlanets\\art\\ (copied there from the chat references).
"""
import os, sys
from PIL import Image, ImageStat
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import iff_clone

OUT = os.path.join(HERE, 'build', 'hoth_loot')
ART_DIR = os.path.join(HERE, 'art')
SIZE = 512
# square Hoth painting (ported from Infinity) used as the frame/shader/template donor
BASE = 'hothatatlg_01_f00_000000000000'
BASE_TEX = 'hothatatlg_01_0000000000000000'

# key, source image, name, description, treatment ('crop' = centre-crop to square, 'pad' = pad to square with
# the border colour, ('top', h) = keep the top h pixels then pad, ('cut', bottom) = drop the bottom rows then pad)
ART = [
    ('astromech_colors', '4.jpg', 'Astromech in Primary Colors',
     'A pop-art study of an R2-series astromech, every panel a different colour. Signed by a Mos Eisley street artist.', 'crop'),
    ('reprogrammed', '5.jpg', 'Reprogrammed',
     'A charcoal sketch of a KX-series Imperial security droid, head bowed. Someone has scratched out the Imperial cog.', ('top', 600)),
    ('hunters_patience', '6.jpg', "The Hunter's Patience",
     'Ink on flimsiplast: a Mandalorian-armored bounty hunter waits. The artist did not sign it twice.', 'pad'),
    ('red_sun_empire', '7.jpg', 'Red Sun Over the Empire',
     'A stormtrooper helmet in brush and ink beneath a red sun. The strokes are hurried, as if painted between patrols.', 'pad'),
    ('biker_scout', '8.jpg', 'Biker Scout at Rest',
     'A scout trooper caught off duty, rifle over the shoulder. Line work in black ink.', 'pad'),
    ('seventy_seven', '9.jpg', 'Seventy-Seven',
     'A retro holoreel poster with starfighters streaking through coloured bands. The numerals mean something to collectors.', 'crop'),
    ('blue_unit', '10.jpg', 'Blue Unit',
     'An astromech droid bursting out of a spray of blue and black. Favoured by Rebel pilots for their ready rooms.', 'crop'),
    ('utinni', '11.jpg', 'Utinni!',
     'Two Jawas make off with a very angry probe droid. A cartoon from the Tatooine funny pages.', 'crop'),
    ('this_is_the_way', '12.jpg', 'This Is the Way',
     'A very small Mandalorian in very large armor. The caption is the creed.', ('cut', 70)),
    ('kessel_run_age_six', '13.jpg', 'Kessel Run, Age Six',
     'A Wookiee and a boy race a toy freighter down a hill. Twelve parsecs, allegedly.', 'crop'),
]


def names():
    return {f'hoth_art_{k}': n for k, _, n, _, _ in ART}


def descs():
    return {f'hoth_art_{k}': d for k, _, _, d, _ in ART}


def out(rel):
    p = os.path.join(OUT, *rel.split('/')); os.makedirs(os.path.dirname(p), exist_ok=True); return p


def border_color(im):
    w, h = im.size
    edge = Image.new('RGB', (w * 2 + h * 2, 1))
    px = list(im.crop((0, 0, w, 1)).getdata()) + list(im.crop((0, h - 1, w, h)).getdata()) + \
        list(im.crop((0, 0, 1, h)).getdata()) + list(im.crop((w - 1, 0, w, h)).getdata())
    edge.putdata(px[:edge.size[0]])
    return tuple(int(v) for v in ImageStat.Stat(edge).median)


def square(im, treatment):
    im = im.convert('RGB')
    if isinstance(treatment, tuple):
        kind, n = treatment
        w, h = im.size
        im = im.crop((0, 0, w, min(h, n))) if kind == 'top' else im.crop((0, 0, w, h - n))
        treatment = 'pad'
    w, h = im.size
    if treatment == 'crop':
        s = min(w, h); l, t = (w - s) // 2, (h - s) // 2
        im = im.crop((l, t, l + s, t + s))
    else:
        s = max(w, h)
        canvas = Image.new('RGB', (s, s), border_color(im))
        canvas.paste(im, ((s - w) // 2, (s - h) // 2))
        im = canvas
    return im.resize((SIZE, SIZE), Image.LANCZOS)


def textures():
    for key, src, *_rest, treatment in ART:
        im = Image.open(os.path.join(ART_DIR, src))
        square(im, treatment).save(out(f'texture/hoth_art_{key}.dds'), pixel_format='DXT1')


def client():
    textures()
    for key, *_ in ART:
        n = f'hoth_art_{key}'
        iff_clone.clone_raw(out(f'shader/{BASE}.sht'), out(f'shader/{n}.sht'),
                            {f'texture/{BASE_TEX}.dds': f'texture/{n}.dds'})
        iff_clone.clone_raw(out(f'appearance/mesh/{BASE}.msh'), out(f'appearance/mesh/{n}.msh'),
                            {f'shader/{BASE}.sht': f'shader/{n}.sht'})
        iff_clone.clone_raw(out(f'appearance/{BASE}.apt'), out(f'appearance/{n}.apt'),
                            {f'appearance/mesh/{BASE}.msh': f'appearance/mesh/{n}.msh'})
        iff_clone.clone(out(f'object/tangible/painting/shared_{BASE}.iff'), out(f'object/tangible/painting/shared_{n}.iff'),
                        {'appearanceFilename': f'appearance/{n}.apt', 'objectName': f'art_n:{n}',
                         'detailedDescription': f'art_d:{n}', 'lookAtText': f'art_n:{n}'})
    print(f'{len(ART)} custom paintings generated')


if __name__ == '__main__':
    client()
