#!/usr/bin/env python3
"""gen_hoth_loot.py — server Lua for the Hoth loot pass (Ender_Hoth_Loot_and_more). Idempotent.

Companion of gen_hoth_loot_client.py (client iffs, strings, CRC table). Generates, under the worktree scripts dir:
  * wearables: Snowtrooper + Alliance Cold Weather armor (10 pieces each, cloned from the stormtrooper set, no faction),
    two backpacks (cloned from backpack_s01)
  * draft schematics + loot schematics + loot items for all 22 armor pieces
  * 12 Hoth paintings: tangible, Architect draft schematic, loot schematic, loot items
  * decor: ported Infinity items and iff_clone'd items as placeable furniture, loot items
  * T-47 snowspeeder: pcd, vehicle, deed, draft schematic, loot schematic, loot item
  * loot groups under loot/groups/bellum/hoth/
Drop hooks live in gen_hoth_mobiles.py (HOOKS below are referenced there).
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import gen_hoth_mobiles as g
import gen_hoth_loot_client as c
import gen_hoth_art as art

ROOT = g.ROOT
FURNITURE_GOT = 8203  # SceneObjectType::FURNITURE — makes a generic tangible placeable/movable in structures


def read(rel):
    return open(os.path.join(ROOT, *rel.split('/')), encoding='utf-8', newline='').read()


def body(text):
    """Drop the GPL header: keep from the first template definition on."""
    i = text.find('object_')
    return text[i:] if i > 0 else text


def write(rel, text):
    return g.write(rel, text)


def luaid(client_path):
    return client_path[:-4].replace('/', '_')


def server_path(client_path):
    d, f = client_path.rsplit('/', 1)
    assert f.startswith('shared_'), client_path
    return f'{d}/{f[7:]}'


# ---------------------------------------------------------------- shared (client) template defs in objects.lua files
SHARED_KIND = {'object/draft_schematic/': 'SharedDraftSchematicObjectTemplate', 'object/intangible/': 'SharedIntangibleObjectTemplate',
               'object/mobile/': 'SharedCreatureObjectTemplate'}


def shared_block(client_path):
    kind = next((v for k, v in SHARED_KIND.items() if client_path.startswith(k)), 'SharedTangibleObjectTemplate')
    lid = luaid(client_path)
    return f'{lid} = {kind}:new {{\n\tclientTemplateFileName = "{client_path}"\n}}\n\nObjectTemplates:addClientTemplate({lid}, "{client_path}")\n'


def ensure_shared(objects_lua_rel, client_paths):
    """Append shared defs that are not yet in an existing objects.lua."""
    path = os.path.join(ROOT, *objects_lua_rel.split('/'))
    s = open(path, encoding='utf-8', newline='').read()
    nl = '\r\n' if '\r\n' in s else '\n'
    add = [p for p in client_paths if luaid(p) + ' =' not in s and f'"{p}"' not in s]
    if add:
        s = s.rstrip('\r\n') + nl + nl + nl.join(shared_block(p).replace('\n', nl) for p in add)
        open(path, 'w', encoding='utf-8', newline='').write(s)
    return len(add)


def new_dir(dir_rel, allobjects_anchor, parent_serverobjects, shared_paths, files):
    """Create <dir>/objects.lua + serverobjects.lua and register both."""
    write(f'{dir_rel}/objects.lua', '-- Generated by NewPlanets/gen_hoth_loot.py\n' + '\n'.join(shared_block(p) for p in shared_paths))
    write(f'{dir_rel}/serverobjects.lua', ''.join(f'includeFile("{dir_rel[7:]}/{f}")\n' for f in files))
    g.register('object/allobjects.lua', f'includeFile("{dir_rel[7:]}/objects.lua")', after_prefix=allobjects_anchor)
    g.register(parent_serverobjects, f'includeFile("{dir_rel[7:]}/serverobjects.lua")')


# ---------------------------------------------------------------- armor
PIECE_NAMES = {
    'snowtrooper': {'belt': 'Snowtrooper Belt', 'bicep_l': 'Snowtrooper Armor Left Bicep', 'bicep_r': 'Snowtrooper Armor Right Bicep',
                    'boots': 'Snowtrooper Armor Boots', 'bracer_l': 'Snowtrooper Armor Left Bracer', 'bracer_r': 'Snowtrooper Armor Right Bracer',
                    'chest_plate': 'Snowtrooper Armor Chest Plate', 'gloves': 'Snowtrooper Gloves', 'helmet': 'Snowtrooper Armor Helmet',
                    'leggings': 'Snowtrooper Armor Leggings', 'backpack': 'Snowtrooper Armor Backpack'},
    'rebel_snow': {'belt': 'Alliance Cold Weather Belt', 'bicep_l': 'Alliance Cold Weather Left Bicep', 'bicep_r': 'Alliance Cold Weather Right Bicep',
                   'boots': 'Alliance Cold Weather Boots', 'bracer_l': 'Alliance Cold Weather Left Bracer', 'bracer_r': 'Alliance Cold Weather Right Bracer',
                   'chest_plate': 'Alliance Cold Weather Padded Vest', 'gloves': 'Alliance Cold Weather Gloves', 'helmet': 'Alliance Cold Weather Headgear',
                   'leggings': 'Alliance Cold Weather Leggings', 'backpack': 'Alliance Cold Weather Backpack'},
}
BACKPACK = {'snowtrooper': 'backpack_snowtrooper', 'rebel_snow': 'backpack_rebel_snow_soldier'}
LOOT_ITEMS = []   # (loot item name, directObjectTemplate)
GROUPS = {}       # group name -> [(item, weight)]


def loot_item(name, template, custom=''):
    LOOT_ITEMS.append((name, template, custom))
    return name


def armor():
    for key, (d, prefix, _) in c.SETS.items():
        wear_files, shared = [], []
        for p in c.PIECES:
            src = c.ST_SRC.get(p, p)
            # wearable
            t = body(read(f'object/tangible/wearables/armor/stormtrooper/armor_stormtrooper_{src}.lua'))
            t = t.replace(f'armor_stormtrooper_{src}', f'{prefix}_{p}').replace('wearables_armor_stormtrooper_', f'wearables_armor_{d}_') \
                 .replace('wearables/armor/stormtrooper/', f'wearables/armor/{d}/')
            t = re.sub(r'\n\tfaction = "Imperial",', '', t)
            assert 'stormtrooper' not in t and 'faction' not in t, (key, p)
            write(f'object/tangible/wearables/armor/{d}/{prefix}_{p}.lua', t)
            wear_files.append(f'{prefix}_{p}.lua'); shared.append(f'object/tangible/wearables/armor/{d}/shared_{prefix}_{p}.iff')
            # draft schematic
            t = body(read(f'object/draft_schematic/clothing/clothing_armor_stormtrooper_{src}.lua'))
            t = t.replace(f'clothing_armor_stormtrooper_{src}', f'clothing_armor_{key}_{p}') \
                 .replace(f'object/tangible/wearables/armor/stormtrooper/armor_stormtrooper_{src}.iff', f'object/tangible/wearables/armor/{d}/{prefix}_{p}.iff')
            t = re.sub(r'customObjectName = "[^"]*"', f'customObjectName = "{PIECE_NAMES[key][p]}"', t)
            assert 'stormtrooper' not in t, (key, p)
            write(f'object/draft_schematic/clothing/clothing_armor_{key}_{p}.lua', t)
            g.register('object/draft_schematic/clothing/serverobjects.lua', f'includeFile("draft_schematic/clothing/clothing_armor_{key}_{p}.lua")')
            # loot schematic
            t = body(read(f'object/tangible/loot/loot_schematic/stormtrooper_{src}_crafted_schematic.lua'))
            t = t.replace(f'stormtrooper_{src}_crafted_schematic', f'{key}_{p}_crafted_schematic') \
                 .replace(f'clothing_armor_stormtrooper_{src}', f'clothing_armor_{key}_{p}')
            t = re.sub(r'customName = "[^"]*"', f'customName = "{PIECE_NAMES[key][p]} Schematic"', t)
            assert 'stormtrooper' not in t, (key, p)
            write(f'object/tangible/loot/loot_schematic/{key}_{p}_crafted_schematic.lua', t)
            g.register('object/tangible/loot/loot_schematic/serverobjects.lua', f'includeFile("tangible/loot/loot_schematic/{key}_{p}_crafted_schematic.lua")')
            loot_item(f'{key}_{p}_schematic', f'object/tangible/loot/loot_schematic/{key}_{p}_crafted_schematic.iff')
        # backpack wearable (cloned from backpack_s01), draft + loot schematic (cloned from the marine backpack)
        bp = BACKPACK[key]
        t = body(read('object/tangible/wearables/backpack/backpack_s01.lua')).replace('backpack_s01', bp)
        write(f'object/tangible/wearables/backpack/{bp}.lua', t)
        g.register('object/tangible/wearables/backpack/serverobjects.lua', f'includeFile("tangible/wearables/backpack/{bp}.lua")')
        t = body(read('object/draft_schematic/clothing/clothing_armor_marine_backpack.lua'))
        t = t.replace('clothing_armor_marine_backpack', f'clothing_armor_{key}_backpack') \
             .replace('object/tangible/wearables/armor/marine/armor_marine_backpack.iff', f'object/tangible/wearables/backpack/{bp}.iff')
        t = re.sub(r'customObjectName = "[^"]*"', f'customObjectName = "{PIECE_NAMES[key]["backpack"]}"', t)
        write(f'object/draft_schematic/clothing/clothing_armor_{key}_backpack.lua', t)
        g.register('object/draft_schematic/clothing/serverobjects.lua', f'includeFile("draft_schematic/clothing/clothing_armor_{key}_backpack.lua")')
        t = body(read('object/tangible/loot/loot_schematic/marine_backpack_crafted_schematic.lua'))
        t = t.replace('marine_backpack_crafted_schematic', f'{key}_backpack_crafted_schematic').replace('clothing_armor_marine_backpack', f'clothing_armor_{key}_backpack')
        t = re.sub(r'customName = "[^"]*"', f'customName = "{PIECE_NAMES[key]["backpack"]} Schematic"', t)
        write(f'object/tangible/loot/loot_schematic/{key}_backpack_crafted_schematic.lua', t)
        g.register('object/tangible/loot/loot_schematic/serverobjects.lua', f'includeFile("tangible/loot/loot_schematic/{key}_backpack_crafted_schematic.lua")')
        loot_item(f'{key}_backpack_schematic', f'object/tangible/loot/loot_schematic/{key}_backpack_crafted_schematic.iff')

        new_dir(f'object/tangible/wearables/armor/{d}', 'includeFile("tangible/wearables/armor/stormtrooper/',
                'object/tangible/wearables/armor/serverobjects.lua', shared, wear_files)
        GROUPS[f'hoth_{key}_schematics'] = [f'{key}_{p}_schematic' for p in c.PIECES] + [f'{key}_backpack_schematic']

    ensure_shared('object/tangible/wearables/backpack/objects.lua',
                  [f'object/tangible/wearables/backpack/shared_{bp}.iff' for bp in BACKPACK.values()])
    ensure_shared('object/draft_schematic/clothing/objects.lua',
                  [f'object/draft_schematic/clothing/shared_clothing_armor_{k}_{p}.iff' for k in c.SETS for p in c.PIECES + ['backpack']])
    ensure_shared('object/tangible/loot/loot_schematic/objects.lua',
                  [f'object/tangible/loot/loot_schematic/shared_{k}_{p}_crafted_schematic.iff' for k in c.SETS for p in c.PIECES + ['backpack']])


# ---------------------------------------------------------------- paintings
def paintings():
    loot_files, loot_shared, draft_files, draft_shared = [], [], [], []
    for key, stem, _, name, _ in c.PAINTINGS:
        tangible = f'object/tangible/painting/{stem}.iff'
        lid = luaid(tangible)
        write(f'object/tangible/painting/{stem}.lua',
              f'{lid} = {luaid(f"object/tangible/painting/shared_{stem}.iff")}:new {{\n}}\n\nObjectTemplates:addTemplate({lid}, "{tangible}")\n')
        g.register('object/tangible/painting/serverobjects.lua', f'includeFile("tangible/painting/{stem}.lua")')
        # Architect draft schematic
        t = body(read('object/draft_schematic/furniture/bestine/painting_bestine_lucky_despot.lua'))
        t = t.replace('object/draft_schematic/furniture/bestine/painting_bestine_lucky_despot.iff', f'object/draft_schematic/furniture/hoth/painting_hoth_{key}.iff') \
             .replace('object/tangible/painting/painting_bestine_lucky_despot.iff', tangible) \
             .replace('furniture_bestine_', 'furniture_hoth_').replace('painting_bestine_lucky_despot', f'painting_hoth_{key}')
        t = re.sub(r'customObjectName = "[^"]*"', f'customObjectName = "Painting: {name}"', t)
        assert 'bestine' not in t and 'lucky' not in t, key
        write(f'object/draft_schematic/furniture/hoth/painting_hoth_{key}.lua', t)
        draft_files.append(f'painting_hoth_{key}.lua'); draft_shared.append(f'object/draft_schematic/furniture/hoth/shared_painting_hoth_{key}.iff')
        # loot schematic
        t = body(read('object/tangible/loot/bestine/bestine_painting_schematic_lucky_despot.lua'))
        t = t.replace('object/tangible/loot/bestine/bestine_painting_schematic_lucky_despot.iff', f'object/tangible/loot/hoth/painting_schematic_hoth_{key}.iff') \
             .replace('object/draft_schematic/furniture/bestine/painting_bestine_lucky_despot.iff', f'object/draft_schematic/furniture/hoth/painting_hoth_{key}.iff') \
             .replace('loot_bestine_', 'loot_hoth_').replace('bestine_painting_schematic_lucky_despot', f'painting_schematic_hoth_{key}') \
             .replace('\ttemplateType = LOOTSCHEMATIC,', f'\ttemplateType = LOOTSCHEMATIC,\n\tcustomName = "Painting Schematic: {name}",')
        assert 'bestine' not in t and 'lucky' not in t, key
        write(f'object/tangible/loot/hoth/painting_schematic_hoth_{key}.lua', t)
        loot_files.append(f'painting_schematic_hoth_{key}.lua'); loot_shared.append(f'object/tangible/loot/hoth/shared_painting_schematic_hoth_{key}.iff')
        loot_item(f'hoth_painting_{key}_schematic', f'object/tangible/loot/hoth/painting_schematic_hoth_{key}.iff')
        loot_item(f'hoth_painting_{key}', tangible)
    # custom boss paintings (gen_hoth_art.py): finished paintings only, no schematic
    for key, *_ in art.ART:
        stem = f'hoth_art_{key}'; tangible = f'object/tangible/painting/{stem}.iff'; lid = luaid(tangible)
        write(f'object/tangible/painting/{stem}.lua',
              f'{lid} = {luaid(f"object/tangible/painting/shared_{stem}.iff")}:new {{\n}}\n\nObjectTemplates:addTemplate({lid}, "{tangible}")\n')
        g.register('object/tangible/painting/serverobjects.lua', f'includeFile("tangible/painting/{stem}.lua")')
        loot_item(stem, tangible)
    GROUPS['hoth_art_rare'] = [f'hoth_art_{key}' for key, *_ in art.ART]
    ensure_shared('object/tangible/painting/objects.lua', [f'object/tangible/painting/shared_{stem}.iff' for _, stem, _, _, _ in c.PAINTINGS]
                  + [f'object/tangible/painting/shared_hoth_art_{key}.iff' for key, *_ in art.ART])
    new_dir('object/draft_schematic/furniture/hoth', 'includeFile("draft_schematic/furniture/', 'object/draft_schematic/furniture/serverobjects.lua', draft_shared, draft_files)
    new_dir('object/tangible/loot/hoth', 'includeFile("tangible/loot/bestine/', 'object/tangible/loot/serverobjects.lua', loot_shared, loot_files)
    GROUPS['hoth_paintings'] = [(f'hoth_painting_{k}_schematic', 7) for k, *_ in c.PAINTINGS] + [(f'hoth_painting_{k}', 1) for k, *_ in c.PAINTINGS]


# ---------------------------------------------------------------- decor
# (client path, needs FURNITURE gameObjectType because it derives from shared_tangible_base)
PORTED_DECOR = [
    ('object/tangible/veteran_reward/shared_frn_plush_tauntaun.iff', True),
    ('object/tangible/collection/reward/shared_col_reward_hoth_tauntaun_head.iff', True),
    ('object/tangible/tcg/series4/shared_decorative_stuffed_tauntaun.iff', True),
    ('object/tangible/tcg/series4/shared_decorative_stuffed_wampa.iff', True),
    ('object/tangible/tcg/series3/shared_decorative_hoth_travel_advertisement.iff', True),
    ('object/tangible/tcg/series8/shared_diorama_atat_attack.iff', True),
    ('object/tangible/tcg/series8/shared_tauntaun_armored_statue.iff', True),
    ('object/tangible/loot/themepark/shared_item_ice_sculpture_wampa.iff', True),
    ('object/tangible/loot/themepark/shared_item_ice_sculpture_tauntaun.iff', True),
    ('object/tangible/loot/themepark/shared_item_wampa_arm.iff', True),
    ('object/tangible/loot/themepark/shared_frn_atat_statuette.iff', True),
    ('object/tangible/loot/themepark/shared_frn_all_atat_chair.iff', True),
    ('object/tangible/loot/themepark/shared_frn_vet_at_at_toy.iff', True),
    ('object/tangible/borrie/wall/shared_cave_ice_wall.iff', False),
] + [(f'object/tangible/loot/toy/shared_hoth_atat_toy_{i:02d}.iff', True) for i in range(1, 11)]
CLONED_DECOR = [f'object/tangible/furniture/hoth/shared_frn_hoth_{row[0]}.iff' for row in c.DECOR]

COMMON = ['frn_plush_tauntaun', 'decorative_stuffed_tauntaun', 'decorative_stuffed_wampa', 'decorative_hoth_travel_advertisement',
          'frn_atat_statuette', 'frn_vet_at_at_toy', 'frn_hoth_snowglobe', 'frn_hoth_snowglobe_gcw'] + [f'hoth_atat_toy_{i:02d}' for i in range(1, 11)]
RARE = ['col_reward_hoth_tauntaun_head', 'diorama_atat_attack', 'tauntaun_armored_statue', 'item_ice_sculpture_wampa', 'item_ice_sculpture_tauntaun',
        'item_wampa_arm', 'frn_all_atat_chair', 'frn_hoth_wampa_rug', 'frn_hoth_snowspeeder_holo', 'frn_hoth_painting_esb_imperial',
        'frn_hoth_painting_esb_neutral', 'frn_hoth_painting_esb_rebel', 'frn_hoth_painting_reward']
ICE = ['cave_ice_wall'] + [f'frn_hoth_stalagmite_{i:02d}' for i in range(1, 10)] + [f'frn_hoth_stalactite_{i:02d}' for i in range(1, 7)]


def decor():
    files, shared = [], []
    for client, needs_got in PORTED_DECOR + [(p, False) for p in CLONED_DECOR]:
        sp = server_path(client); stem = sp.rsplit('/', 1)[1][:-4]
        lid = luaid(sp)
        extra = f'\tgameObjectType = {FURNITURE_GOT},\n' if needs_got else ''
        write(f'object/tangible/furniture/hoth/{stem}.lua', f'{lid} = {luaid(client)}:new {{\n{extra}}}\n\nObjectTemplates:addTemplate({lid}, "{sp}")\n')
        files.append(f'{stem}.lua'); shared.append(client)
        loot_item(f'hoth_decor_{stem}', sp)
    new_dir('object/tangible/furniture/hoth', 'includeFile("tangible/furniture/', 'object/tangible/furniture/serverobjects.lua', shared, files)
    GROUPS['hoth_decor_common'] = [f'hoth_decor_{s}' for s in COMMON]
    GROUPS['hoth_decor_rare'] = [f'hoth_decor_{s}' for s in RARE]  # vehicles moved to hoth_vehicle_* groups
    GROUPS['hoth_ice_decor'] = [f'hoth_decor_{s}' for s in ICE]
    known = {f'hoth_decor_{server_path(p).rsplit("/", 1)[1][:-4]}' for p, _ in PORTED_DECOR} | {f'hoth_decor_{r[0] if r[0].startswith("frn_hoth") else "frn_hoth_" + r[0]}' for r in c.DECOR}
    for grp in ('hoth_decor_common', 'hoth_decor_rare', 'hoth_ice_decor'):
        for it in GROUPS[grp]:
            name = it[0] if isinstance(it, tuple) else it
            assert name in known, name


# ---------------------------------------------------------------- snowspeeder
def snowspeeder():
    write('object/intangible/vehicle/snowspeeder.lua',
          'object_intangible_vehicle_snowspeeder = object_intangible_vehicle_shared_snowspeeder:new {\n}\n\n'
          'ObjectTemplates:addTemplate(object_intangible_vehicle_snowspeeder, "object/intangible/vehicle/snowspeeder.iff")\n')
    g.register('object/intangible/vehicle/serverobjects.lua', 'includeFile("intangible/vehicle/snowspeeder.lua")')
    ensure_shared('object/intangible/vehicle/objects.lua', ['object/intangible/vehicle/shared_snowspeeder.iff'])

    write('object/mobile/vehicle/snowspeeder.lua',
          'object_mobile_vehicle_snowspeeder = object_mobile_vehicle_shared_snowspeeder:new {\n\ttemplateType = VEHICLE,\n'
          '\tdecayRate = 15, -- Damage tick per decay cycle\n\tdecayCycle = 600 -- Time in seconds per cycle\n}\n\n'
          'ObjectTemplates:addTemplate(object_mobile_vehicle_snowspeeder, "object/mobile/vehicle/snowspeeder.iff")\n')
    g.register('object/mobile/vehicle/serverobjects.lua', 'includeFile("mobile/vehicle/snowspeeder.lua")')
    ensure_shared('object/mobile/vehicle/objects.lua', ['object/mobile/vehicle/shared_snowspeeder.iff'])

    t = body(read('object/tangible/deed/vehicle_deed/landspeeder_x34_deed.lua'))
    t = t.replace('landspeeder_x34_deed', 'snowspeeder_deed').replace('landspeeder_x34_pcd', 'snowspeeder').replace('landspeeder_x34', 'snowspeeder')
    assert 'x34' not in t
    write('object/tangible/deed/vehicle_deed/snowspeeder_deed.lua', t)
    g.register('object/tangible/deed/vehicle_deed/serverobjects.lua', 'includeFile("tangible/deed/vehicle_deed/snowspeeder_deed.lua")')
    ensure_shared('object/tangible/deed/vehicle_deed/objects.lua', ['object/tangible/deed/vehicle_deed/shared_snowspeeder_deed.iff'])

    t = body(read('object/draft_schematic/vehicle/civilian/landspeeder_x34.lua'))
    t = t.replace('landspeeder_x34_deed', 'snowspeeder_deed').replace('landspeeder_x34', 'snowspeeder')
    t = re.sub(r'customObjectName = "[^"]*"', 'customObjectName = "T-47 Snowspeeder"', t)
    t = t.replace('resourceQuantities = {1125, 3125}', 'resourceQuantities = {1500, 3500}')
    assert 'x34' not in t
    write('object/draft_schematic/vehicle/civilian/snowspeeder.lua', t)
    g.register('object/draft_schematic/vehicle/civilian/serverobjects.lua', 'includeFile("draft_schematic/vehicle/civilian/snowspeeder.lua")')
    ensure_shared('object/draft_schematic/vehicle/civilian/objects.lua', ['object/draft_schematic/vehicle/civilian/shared_snowspeeder.iff'])

    write('object/tangible/loot/loot_schematic/loot_schem_snowspeeder.lua',
          'object_tangible_loot_loot_schematic_loot_schem_snowspeeder = object_tangible_loot_loot_schematic_shared_loot_schem_snowspeeder:new {\n'
          '\ttemplateType = LOOTSCHEMATIC,\n\tcustomName = "T-47 Snowspeeder Schematic",\n'
          '\tobjectMenuComponent = "LootSchematicMenuComponent",\n\tattributeListComponent = "LootSchematicAttributeListComponent",\n'
          '\trequiredSkill = "crafting_artisan_engineering_04",\n'
          '\ttargetDraftSchematic = "object/draft_schematic/vehicle/civilian/snowspeeder.iff",\n\ttargetUseCount = 1,\n}\n\n'
          'ObjectTemplates:addTemplate(object_tangible_loot_loot_schematic_loot_schem_snowspeeder, "object/tangible/loot/loot_schematic/loot_schem_snowspeeder.iff")\n')
    g.register('object/tangible/loot/loot_schematic/serverobjects.lua', 'includeFile("tangible/loot/loot_schematic/loot_schem_snowspeeder.lua")')
    ensure_shared('object/tangible/loot/loot_schematic/objects.lua', ['object/tangible/loot/loot_schematic/shared_loot_schem_snowspeeder.iff'])
    loot_item('snowspeeder_schematic', 'object/tangible/loot/loot_schematic/loot_schem_snowspeeder.iff')


# ---------------------------------------------------------------- loot items and groups
def loot_items():
    for name, tmpl, custom in LOOT_ITEMS:
        write(f'loot/items/bellum/hoth/{name}.lua', f'''{name} = {{
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "{custom}",
	directObjectTemplate = "{tmpl}",
	craftingValues = {{}},
	customizationStringNames = {{}},
	customizationValues = {{}}
}}

addLootItemTemplate("{name}", {name})
''')
        g.register('loot/items.lua', f'includeFile("items/bellum/hoth/{name}.lua")', after_prefix='includeFile("items/bellum/')


def weights(items):
    """Distribute 10,000,000 over items; items may be (name, relative weight) tuples."""
    items = [(i, 1) if isinstance(i, str) else i for i in items]
    tot = sum(w for _, w in items)
    out = [(n, 10000000 * w // tot) for n, w in items]
    out[-1] = (out[-1][0], 10000000 - sum(w for _, w in out[:-1]))
    return out


def groups():
    for name, items in GROUPS.items():
        rows = ',\n'.join(f'\t\t{{itemTemplate = "{n}", weight = {w}}}' for n, w in weights(items))
        write(f'loot/groups/bellum/hoth/{name}.lua', f'''-- Generated by NewPlanets/gen_hoth_loot.py. Weights total 10,000,000.
{name} = {{
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {{
{rows}
	}}
}}

addLootGroupTemplate("{name}", {name})
''')
        g.register('loot/groups.lua', f'includeFile("groups/bellum/hoth/{name}.lua")', after_prefix='includeFile("groups/bellum/')


if __name__ == '__main__':
    armor(); paintings(); decor()
    import gen_hoth_vehicles
    gen_hoth_vehicles.server(g, write, body, read, ensure_shared, loot_item, GROUPS)
    loot_items(); groups()
    print(f'{len(LOOT_ITEMS)} loot items, groups: ' + ', '.join(f'{k}({len(v)})' for k, v in GROUPS.items()))
