#!/usr/bin/env python3
"""Regenerate ASSET_LOG.md from audit/<planet>_closure.tsv (run after dep_closure.py)."""
import csv
PLANETS = ['taanab', 'hoth', 'kashyyyk']
WHY = {'terrain/': 'terrain layer/ramp', 'snapshot/': 'static world objects',
       'object/': 'object template referenced by snapshot/terrain',
       'appearance/': 'appearance chain of a ported object',
       'texture/ui_map': 'planet map', 'texture/': 'texture of a ported shader',
       'shader/': 'shader of a ported mesh'}
FORCE = ('terrain/', 'snapshot/', 'texture/ui_map')

def load(p):
    return list(csv.reader(open(f'audit/{p}_closure.tsv'), delimiter='\t'))[1:]

out = ["# ASSET_LOG — our_planets.tre", "",
       r"Source client: **SWG Infinity** (`C:\SWG Infinity\Live`, load order from `swgemu_live.cfg`).",
       r"Target client: **Bellum Gero** (`C:\BellumGero`, top TRE `bg_worldbuilder.tre` @ priority 28).",
       "Generated by `dep_closure.py` + `make_asset_log.py`; full closures in `audit/<planet>_closure.tsv`.", "",
       "Status: **PLANNED** — nothing packed yet. Shared assets where Infinity differs from BG keep BG's version by default.", ""]
missing = {}
for p in PLANETS:
    rows = load(p)
    port = [r for r in rows if r[2] == 'port']
    force = [r for r in rows if r[2] == 'in_bg_differs' and r[0].startswith(FORCE)]
    review = [r for r in rows if r[2] == 'in_bg_differs' and r not in force]
    for r in rows:
        if r[2] == 'missing':
            missing.setdefault(r[0], []).append(p)
    out += [f"## {p.capitalize()} — {len(port)} new + {len(force)} override", "",
            "| path | source TRE | action | why | fixes |", "|---|---|---|---|---|"]
    for r in port + force:
        w = next((v for k, v in WHY.items() if r[0].startswith(k)), 'dependency')
        out.append(f"| `{r[0]}` | {r[1]} | {'new' if r[2] == 'port' else 'override BG'} | {w} | — |")
    if review:
        out += ["", f"<details><summary>{len(review)} shared assets differ from BG (kept BG)</summary>", ""]
        out += [f"- `{r[0]}` ({r[1]})" for r in review] + ["", "</details>"]
    out.append("")
out += ["## MISSING", "", "Referenced, but in neither client (dead refs in the source data):", ""]
out += [f"- `{k}` — {', '.join(v)}" for k, v in sorted(missing.items())]
open('ASSET_LOG.md', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('ASSET_LOG.md written')
